version: '3.1'

services:

  wordpress:
#    image: wordpress
    image: wpdiaries/wordpress-xdebug:6.0.1-php8.1-apache
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

      XDEBUG_CONFIG: start_with_request=yes client_host=host.docker.internal client_port=9000
    volumes:
      - .:/var/www/html
    networks:
      - wp-network
  db:
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp-network
volumes:
  db:
  wp-content:
networks:
  wp-network:
    driver: bridge
